// 20 social-first caption style presets.
// Each preset compiles to ASS subtitle styling for FFmpeg burn-in,
// and a CSS preview spec for the in-browser overlay.

export type CaptionStyle = {
  id: string;
  name: string;
  tagline: string;
  // Defaults — user can override via controls
  font: string; // ASS font name (must be registered/embedded for ffmpeg)
  fontSizeRatio: number; // relative to video height (e.g. 0.06 = 6% of height)
  primary: string; // hex (text fill)
  highlight: string; // hex (active word)
  outline: string; // hex
  outlineWidth: number;
  shadow: number;
  bg: string | null; // hex w/ alpha or null
  bgPadding: number;
  bold: boolean;
  italic: boolean;
  uppercase: boolean;
  position: "bottom" | "center" | "top";
  marginV: number; // 0..0.5 ratio of height
  letterSpacing: number;
  // Animation
  anim: "none" | "pop" | "slide" | "fade" | "type" | "bounce" | "shake";
  // Word grouping
  maxWordsPerLine: number;
  highlightMode: "word" | "line" | "none";
};

export const CAPTION_STYLES: CaptionStyle[] = [
  {
    id: "viral-pop",
    name: "Viral Pop",
    tagline: "Bold yellow word-pop, MrBeast energy",
    font: "Impact",
    fontSizeRatio: 0.07,
    primary: "#FFFFFF",
    highlight: "#FFE600",
    outline: "#000000",
    outlineWidth: 4,
    shadow: 2,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.18,
    letterSpacing: 0,
    anim: "pop",
    maxWordsPerLine: 3,
    highlightMode: "word",
  },
  {
    id: "tiktok-classic",
    name: "TikTok Classic",
    tagline: "White on black box, every creator's go-to",
    font: "Arial",
    fontSizeRatio: 0.045,
    primary: "#FFFFFF",
    highlight: "#FFFFFF",
    outline: "#000000",
    outlineWidth: 0,
    shadow: 0,
    bg: "#000000CC",
    bgPadding: 12,
    bold: true,
    italic: false,
    uppercase: false,
    position: "bottom",
    marginV: 0.12,
    letterSpacing: 0,
    anim: "fade",
    maxWordsPerLine: 6,
    highlightMode: "none",
  },
  {
    id: "neon-glow",
    name: "Neon Glow",
    tagline: "Cyberpunk magenta with electric outline",
    font: "Arial Black",
    fontSizeRatio: 0.06,
    primary: "#FF2EC4",
    highlight: "#00F0FF",
    outline: "#1A0030",
    outlineWidth: 3,
    shadow: 6,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.2,
    letterSpacing: 2,
    anim: "pop",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "karaoke-fire",
    name: "Karaoke Fire",
    tagline: "Word-by-word orange highlight",
    font: "Impact",
    fontSizeRatio: 0.06,
    primary: "#FFFFFF",
    highlight: "#FF6B00",
    outline: "#000000",
    outlineWidth: 3,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.22,
    letterSpacing: 0,
    anim: "pop",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "minimal-white",
    name: "Minimal White",
    tagline: "Clean, low-key, podcast-friendly",
    font: "Helvetica",
    fontSizeRatio: 0.04,
    primary: "#FFFFFF",
    highlight: "#FFFFFF",
    outline: "#000000",
    outlineWidth: 2,
    shadow: 1,
    bg: null,
    bgPadding: 0,
    bold: false,
    italic: false,
    uppercase: false,
    position: "bottom",
    marginV: 0.08,
    letterSpacing: 0,
    anim: "fade",
    maxWordsPerLine: 8,
    highlightMode: "none",
  },
  {
    id: "instagram-story",
    name: "IG Story",
    tagline: "Soft white pill on translucent dark",
    font: "Helvetica",
    fontSizeRatio: 0.048,
    primary: "#FFFFFF",
    highlight: "#FFFFFF",
    outline: "#000000",
    outlineWidth: 0,
    shadow: 0,
    bg: "#00000099",
    bgPadding: 16,
    bold: true,
    italic: false,
    uppercase: false,
    position: "center",
    marginV: 0.25,
    letterSpacing: 0,
    anim: "slide",
    maxWordsPerLine: 5,
    highlightMode: "none",
  },
  {
    id: "shake-shock",
    name: "Shake Shock",
    tagline: "Glitchy, jittery, attention-grabbing",
    font: "Impact",
    fontSizeRatio: 0.065,
    primary: "#FFFFFF",
    highlight: "#FF0040",
    outline: "#000000",
    outlineWidth: 4,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.2,
    letterSpacing: 1,
    anim: "shake",
    maxWordsPerLine: 3,
    highlightMode: "word",
  },
  {
    id: "bounce-bubble",
    name: "Bounce Bubble",
    tagline: "Playful, kid-content vibe",
    font: "Comic Sans MS",
    fontSizeRatio: 0.06,
    primary: "#FFE600",
    highlight: "#FF2EC4",
    outline: "#000000",
    outlineWidth: 4,
    shadow: 2,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: false,
    position: "center",
    marginV: 0.2,
    letterSpacing: 0,
    anim: "bounce",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "typewriter-mono",
    name: "Typewriter",
    tagline: "Letter-by-letter mono reveal",
    font: "Courier New",
    fontSizeRatio: 0.045,
    primary: "#00FF66",
    highlight: "#00FF66",
    outline: "#000000",
    outlineWidth: 2,
    shadow: 0,
    bg: "#000000CC",
    bgPadding: 10,
    bold: true,
    italic: false,
    uppercase: false,
    position: "bottom",
    marginV: 0.1,
    letterSpacing: 1,
    anim: "type",
    maxWordsPerLine: 7,
    highlightMode: "none",
  },
  {
    id: "podcast-pro",
    name: "Podcast Pro",
    tagline: "Two-line, big readable",
    font: "Helvetica",
    fontSizeRatio: 0.055,
    primary: "#FFFFFF",
    highlight: "#FFE600",
    outline: "#000000",
    outlineWidth: 3,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: false,
    position: "center",
    marginV: 0.18,
    letterSpacing: 0,
    anim: "fade",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "gradient-pink",
    name: "Gradient Pink",
    tagline: "Pink-to-violet word highlight",
    font: "Arial Black",
    fontSizeRatio: 0.06,
    primary: "#FFFFFF",
    highlight: "#FF2EC4",
    outline: "#1A0030",
    outlineWidth: 3,
    shadow: 4,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.2,
    letterSpacing: 1,
    anim: "pop",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "yt-shorts",
    name: "YT Shorts",
    tagline: "Big white, thick black stroke",
    font: "Arial Black",
    fontSizeRatio: 0.07,
    primary: "#FFFFFF",
    highlight: "#FFFFFF",
    outline: "#000000",
    outlineWidth: 5,
    shadow: 2,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.2,
    letterSpacing: 0,
    anim: "pop",
    maxWordsPerLine: 3,
    highlightMode: "none",
  },
  {
    id: "reels-soft",
    name: "Reels Soft",
    tagline: "Gentle white box, no aggression",
    font: "Helvetica",
    fontSizeRatio: 0.042,
    primary: "#1A1A1A",
    highlight: "#1A1A1A",
    outline: "#FFFFFF",
    outlineWidth: 0,
    shadow: 0,
    bg: "#FFFFFFEE",
    bgPadding: 14,
    bold: true,
    italic: false,
    uppercase: false,
    position: "bottom",
    marginV: 0.13,
    letterSpacing: 0,
    anim: "fade",
    maxWordsPerLine: 6,
    highlightMode: "none",
  },
  {
    id: "trap-red",
    name: "Trap Red",
    tagline: "Red highlight, hype trailer feel",
    font: "Impact",
    fontSizeRatio: 0.065,
    primary: "#FFFFFF",
    highlight: "#FF1744",
    outline: "#000000",
    outlineWidth: 3,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.2,
    letterSpacing: 2,
    anim: "pop",
    maxWordsPerLine: 3,
    highlightMode: "word",
  },
  {
    id: "lime-flash",
    name: "Lime Flash",
    tagline: "Lime active word, dark drop",
    font: "Arial Black",
    fontSizeRatio: 0.06,
    primary: "#FFFFFF",
    highlight: "#C6FF00",
    outline: "#000000",
    outlineWidth: 3,
    shadow: 2,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.22,
    letterSpacing: 0,
    anim: "pop",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "vibe-pastel",
    name: "Vibe Pastel",
    tagline: "Soft pastel pink + cream",
    font: "Helvetica",
    fontSizeRatio: 0.05,
    primary: "#FFF1E6",
    highlight: "#FFB5A7",
    outline: "#3B2A2A",
    outlineWidth: 2,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: false,
    position: "center",
    marginV: 0.2,
    letterSpacing: 0,
    anim: "fade",
    maxWordsPerLine: 5,
    highlightMode: "word",
  },
  {
    id: "drama-italic",
    name: "Drama Italic",
    tagline: "Italic serif-feel, storytelling",
    font: "Georgia",
    fontSizeRatio: 0.05,
    primary: "#FFFFFF",
    highlight: "#FFE600",
    outline: "#000000",
    outlineWidth: 2,
    shadow: 3,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: true,
    uppercase: false,
    position: "center",
    marginV: 0.2,
    letterSpacing: 0,
    anim: "slide",
    maxWordsPerLine: 6,
    highlightMode: "none",
  },
  {
    id: "ig-bold-black",
    name: "IG Bold Black",
    tagline: "Black bg pill, white bold text",
    font: "Arial Black",
    fontSizeRatio: 0.05,
    primary: "#FFFFFF",
    highlight: "#FFE600",
    outline: "#000000",
    outlineWidth: 0,
    shadow: 0,
    bg: "#000000",
    bgPadding: 18,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.22,
    letterSpacing: 1,
    anim: "slide",
    maxWordsPerLine: 4,
    highlightMode: "word",
  },
  {
    id: "cinematic-cap",
    name: "Cinematic",
    tagline: "All-caps, wide spacing, classy",
    font: "Helvetica",
    fontSizeRatio: 0.038,
    primary: "#FFFFFF",
    highlight: "#FFFFFF",
    outline: "#000000",
    outlineWidth: 1,
    shadow: 4,
    bg: null,
    bgPadding: 0,
    bold: false,
    italic: false,
    uppercase: true,
    position: "bottom",
    marginV: 0.08,
    letterSpacing: 4,
    anim: "fade",
    maxWordsPerLine: 8,
    highlightMode: "none",
  },
  {
    id: "hype-mega",
    name: "Hype Mega",
    tagline: "Massive word-at-a-time, max attention",
    font: "Impact",
    fontSizeRatio: 0.11,
    primary: "#FFE600",
    highlight: "#FF2EC4",
    outline: "#000000",
    outlineWidth: 6,
    shadow: 0,
    bg: null,
    bgPadding: 0,
    bold: true,
    italic: false,
    uppercase: true,
    position: "center",
    marginV: 0.4,
    letterSpacing: 2,
    anim: "pop",
    maxWordsPerLine: 1,
    highlightMode: "word",
  },
];
